### ISSUE TITLE
io.load: Not clear in which space streamlines are loaded

### ISSUE THREAD

**Issue by gagdiez** [sdeslauriers/streamlines#4]
The function io.load loads functions in different spaces depending if there's an affine present or not. This is not obvious, and the documentation of io.load does not state it.

I would to suggest to:
- document the function
-  always load the streamlines in the same space... or add a parameter to the function to specify in which space they should be loaded.

**Comment by sdeslauriers** [comment]
Yes, I agree it's a problem. I am working on a solution to this that will work for both `streamlines` and `nimesh`. Should be available soon.

**Comment by sdeslauriers** [comment]
A possible fix is available in the `use-coord` branch. `load` now always loads in native RAS space (this is coherent with the assumptions of nibabel). To get the streamlines in voxel space, you can use the `transform_to` method of `Streamlines`. Note that this is only possible if the file contains a `vox_to_rasmm` transform.

**Comment by sdeslauriers** [comment]
A solution is included in #12.
