### ISSUE TITLE
Meta information of streamlines is lost in load

### ISSUE THREAD

**Issue by gagdiez** [sdeslauriers/streamlines#5]
When doing streamlines.io.load(), it's not possible to access the 'reference_volume_shape' and 'voxel_size' setted using streamlines.io.save()

**Comment by gagdiez** [comment]
I came to report this issue, turns out it was already opened. Lets fix it, cause I need. I think we should change the constructor of Streamlines to take an affine (it currently does), voxel_size, and shape of the volume. Then this should be reflected in the load and save. I'll do it now and submit a pull request.

**Comment by sdeslauriers** [comment]
I am not sure those properties belong on the `Streamlines` object. Does it make sense to have a voxel_size if your streamlines are in world coordinates? Maybe this should be with the coordinate system information?

**Comment by gagdiez** [comment]
Tell me more about this coordinate system. Or link me to some code in
nimesh.

**Comment by sdeslauriers** [comment]
I have a new class `CoordinateSystem` that keeps a space (e.g. VOXEL, NATIVE, ...) and axes (RAS, LPS, ...). I also have affines that transform from one coordinate system to another. The idea is to write something like
```
streamlines.transform_to(VOXEL)
mesh.transform_to(VOXEL)
```
and you are sure that your streamlines and mesh are in the same space.

Maybe `CoordinateSystem` could also have `voxel_size` and `shape` if it is in VOXEL space?

**Comment by sdeslauriers** [comment]
The proposed changes are in the `use-coord` branch. You should now be able to do
```
import streamlines as sl
import nicoord as nic

streamlines = sl.io.load('my-streamlines.trk')
streamlines.transform_to(nic.coord('voxel', 'ras')) # This is important because streamlines are loaded in native RAS by default.

# These two statements only work if the streamlines are in voxel space.
print(streamlines.coordinate_system.voxel_sizes)
print(streamlines.coordinate_system.shape)
```
